// Code generated by protoc-gen-go from "log_message.proto"
// DO NOT EDIT!

package golog

import proto "goprotobuf.googlecode.com/hg/proto"
import "math"
import "os"

// Reference proto, math & os imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf
var _ os.Error

type LogMessage struct {
	Level            *int32               `protobuf:"varint,1,req" json:"Level,omitempty"`
	Nanoseconds      *int64               `protobuf:"varint,2,req" json:"Nanoseconds,omitempty"`
	Message          *string              `protobuf:"bytes,3,req" json:"Message,omitempty"`
	Location         *LogMessage_Location `protobuf:"group,4,opt" json:"location,omitempty"`
	XXX_unrecognized []byte               `json:",omitempty"`
}

func (this *LogMessage) Reset()         { *this = LogMessage{} }
func (this *LogMessage) String() string { return proto.CompactTextString(this) }

type LogMessage_Location struct {
	Package          *string `protobuf:"bytes,5,opt" json:"Package,omitempty"`
	File             *string `protobuf:"bytes,6,opt" json:"File,omitempty"`
	Function         *string `protobuf:"bytes,7,opt" json:"Function,omitempty"`
	Line             *int32  `protobuf:"varint,8,opt" json:"Line,omitempty"`
	XXX_unrecognized []byte  `json:",omitempty"`
}

func (this *LogMessage_Location) Reset()         { *this = LogMessage_Location{} }
func (this *LogMessage_Location) String() string { return proto.CompactTextString(this) }

func init() {
}
